# Project configuration
general:
  projectName: 'RiskManagement'
  productiveBranch: 'main'

# Stage configuration
stages:
  productionDeployment:
    cfTargets:
    - org: '77b08db6trial'
      space: 'dev'
      appName: 'RiskManagement-ik-trial'
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      credentialsId: 'cfdeploy'
